spring.application.name=TodoApp



#spring.application.name=DiscoYourselfInGoa 



server.port=8082

# JPA and DataSource configuration
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:mysql://localhost:3306/StudentService?createDatabaseIfNotExist=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.username=root
spring.datasource.password=kalyani
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update